/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.Shop;

/**
 *
 * @author XFAO03
 */
public class CheckOutFormView extends javax.swing.JFrame {

    /**
     * Creates new form CheckOutFormView
     */
    public CheckOutFormView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCheckOut = new javax.swing.JTable();
        lblDate = new javax.swing.JLabel();
        lblCheckOutNumber = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblTotalPrice = new javax.swing.JLabel();
        lblSelectPaymentMethodText = new javax.swing.JLabel();
        lblClientName = new javax.swing.JLabel();
        lblCreditCardText = new javax.swing.JLabel();
        lblCashText = new javax.swing.JLabel();
        jrbCash = new javax.swing.JRadioButton();
        jrbCreditCard = new javax.swing.JRadioButton();
        btnPay = new javax.swing.JButton();
        lblClientNameText = new javax.swing.JLabel();
        lblTotalPriceText = new javax.swing.JLabel();
        lblCheckOutNumberText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableCheckOut.setAutoCreateRowSorter(true);
        jTableCheckOut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"123", "Microprocesador intel i5", "Intel", "30", "1.000,00", "1121.00"},
                {"456", "Motherboard Bk50", "Asus", "30", "5.000,00", "6230.00"},
                {"789", "Memory Ram ddr5 16 GB", "Kingston", "60", "3.000,00", "4150.00"},
                {"123", null, null, null, null, null},
                {"333", null, null, null, null, null},
                {"333", null, null, null, null, null},
                {"222", null, null, null, null, null},
                {"444", null, null, null, null, null},
                {"333", null, null, null, null, null},
                {"3333", null, null, null, null, null},
                {"4444", null, null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Brand", "Quantity", "Price", "FinalPrice"
            }
        ));
        jTableCheckOut.setAutoscrolls(false);
        jTableCheckOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableCheckOut.setGridColor(new java.awt.Color(255, 255, 255));
        jTableCheckOut.setShowGrid(true);
        jTableCheckOut.setShowHorizontalLines(true);
        jTableCheckOut.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTableCheckOut);
        if (jTableCheckOut.getColumnModel().getColumnCount() > 0) {
            jTableCheckOut.getColumnModel().getColumn(0).setMinWidth(0);
            jTableCheckOut.getColumnModel().getColumn(0).setMaxWidth(50);
            jTableCheckOut.getColumnModel().getColumn(1).setMaxWidth(400);
            jTableCheckOut.getColumnModel().getColumn(2).setMaxWidth(100);
            jTableCheckOut.getColumnModel().getColumn(3).setMaxWidth(50);
            jTableCheckOut.getColumnModel().getColumn(4).setMaxWidth(100);
            jTableCheckOut.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 590, 200));

        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDate.setText("Saturday 9/2/2023");
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        lblCheckOutNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCheckOutNumber.setText("435232");
        jPanel1.add(lblCheckOutNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 90, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 5, -1, -1));

        lblTotalPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalPrice.setText("1500.00");
        jPanel2.add(lblTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        lblSelectPaymentMethodText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSelectPaymentMethodText.setText("SELECT PAYMENT METHOD");
        jPanel2.add(lblSelectPaymentMethodText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        lblClientName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblClientName.setText("Fernando Osorio");
        jPanel2.add(lblClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        lblCreditCardText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCreditCardText.setText("CREDIT CARD");
        jPanel2.add(lblCreditCardText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        lblCashText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCashText.setText("CASH");
        jPanel2.add(lblCashText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        jPanel2.add(jrbCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));
        jPanel2.add(jrbCreditCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        btnPay.setText("PAY");
        jPanel2.add(btnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        lblClientNameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblClientNameText.setText("Client name:");
        jPanel2.add(lblClientNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        lblTotalPriceText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalPriceText.setText("Total price: $ ");
        jPanel2.add(lblTotalPriceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 590, 240));

        lblCheckOutNumberText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCheckOutNumberText.setText("CHECKOUT N°: ");
        jPanel1.add(lblCheckOutNumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOutFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOutFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOutFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOutFormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOutFormView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPay;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCheckOut;
    private javax.swing.JRadioButton jrbCash;
    private javax.swing.JRadioButton jrbCreditCard;
    private javax.swing.JLabel lblCashText;
    private javax.swing.JLabel lblCheckOutNumber;
    private javax.swing.JLabel lblCheckOutNumberText;
    private javax.swing.JLabel lblClientName;
    private javax.swing.JLabel lblClientNameText;
    private javax.swing.JLabel lblCreditCardText;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblSelectPaymentMethodText;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JLabel lblTotalPriceText;
    // End of variables declaration//GEN-END:variables
}
